apiVersion: v1
kind: Pod
metadata:
  name: nginx-minimal
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "50Mi"
        cpu: "250m"
      requests:
        memory: "25Mi"
        cpu: "250m"
