[tools]
go = "1.26"
kubectl = "latest"
helm = "latest"
kustomize = "latest"
kind = "latest"
k9s = "latest"
tilt = "latest"
ko = "latest"
kubectx = "latest"
envsubst = "latest"
terraform = "latest"
jq = "latest"
yq = "latest"
act = "latest"
gcloud = "latest"

[env]
GOBIN = "{{config_root}}/go/bin"
GOPATH = "{{config_root}}/go"
_.path = ["{{config_root}}/go/bin"]

[tasks.bootstrap]
description = "Initialize tools & dependencies" 
run = [
    "go install sigs.k8s.io/cloud-provider-kind@v0.2.0",
    "gcloud components install gke-gcloud-auth-plugin"
]