[tools]
go = "1.22"
kubectl = "latest"
helm = "latest"
kustomize = "latest"
kind = "latest"
k9s = "latest"
tilt = "latest"
ko = "latest"
kubectx = "latest"
envsubst = "latest"
terraform = "latest"
jq = "latest"
yq = "latest"
act = "latest"
gcloud = "latest"

[env]
GOBIN = "{{config_root}}/bin"
PATH = "{{config_root}}/bin:{{env.PATH}}"

[tasks.bootstrap]
description = "Initialize tools & dependencies"
run = "go install sigs.k8s.io/cloud-provider-kind@v0.2.0"